name: CI Pipeline

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint:
        name: ESLint + Prettier Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run ESLint
              run: yarn lint

            - name: Run Prettier
              run: yarn prettier

    test:
        name: Unit Tests (Vitest)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Run Vitest
              run: yarn test

    build:
        name: Build Project
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Build Project
              run: yarn build

            - name: Archive Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: dist/
                  retention-days: 7

    e2e:
        name: E2E Tests on Built Version
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install Dependencies
              run: yarn install --frozen-lockfile

            - name: Download Build Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: dist/

            - name: Serve Build Locally (Vite)
              run: yarn preview --host &

            - name: Wait for Server to Start
              run: npx wait-on http://localhost:4173

            - name: Run Cypress E2E Tests (excluding product.cy.ts)
              run: yarn cypress run --config baseUrl=http://localhost:4173 --spec "cypress/e2e/**/*.cy.ts,!cypress/e2e/product.cy.ts"
